version: '2.1'

services:
  bootstrap:
    container_name: bootstrap
    image: docker.io/bitnami/mariadb-galera:10.6
    volumes:
      - 'mariadb_galera_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      #- MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://
      - MARIADB_GALERA_CLUSTER_NAME=galera_cluster
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_GALERA_MARIABACKUP_USER=backup
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup
      - MARIADB_REPLICATION_USER=replica
      - MARIADB_REPLICATION_PASSWORD=replica
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    networks:
      - cluster

  node:
    image: docker.io/bitnami/mariadb-galera:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=no
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://bootstrap
      - MARIADB_GALERA_CLUSTER_NAME=galera_cluster
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_GALERA_MARIABACKUP_USER=backup
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup
      - MARIADB_REPLICATION_USER=replica
      - MARIADB_REPLICATION_PASSWORD=replica
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    networks: 
      - cluster
    depends_on:
      - bootstrap

volumes:
  mariadb_galera_data:
    driver: local

networks:
  cluster:
    driver: bridge
